# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about',
                'verbose_name': '\u041e_\u043d\u0430\u0441',
                'verbose_name_plural': '\u041e_\u043d\u0430\u0441',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('text_button', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, upload_to=b'')),
            ],
            options={
                'db_table': 'banner',
                'verbose_name': '\u0411\u0430\u043d\u043d\u0435\u0440',
                'verbose_name_plural': '\u0411\u0430\u043d\u043d\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Img_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
            options={
                'db_table': 'img_project',
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430_\u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438_\u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
                'verbose_name': '\u041e_\u043d\u0430\u0441',
                'verbose_name_plural': '\u041e_\u043d\u0430\u0441',
            },
        ),
        migrations.AddField(
            model_name='img_project',
            name='project_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solar.Project'),
        ),
    ]
