# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_auto_20170618_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_project',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
