# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_img_project_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='head_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='head_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
