# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_auto_20170618_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('project_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solar.Project')),
            ],
            options={
                'db_table': 'category_project',
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f_\u043f\u0440\u043e\u0435\u043a\u0442\u044b',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438_\u043f\u0440\u043e\u0435\u043a\u0442\u044b',
            },
        ),
        migrations.AlterModelOptions(
            name='img_project',
            options={'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430_\u043f\u0440\u043e\u0435\u043a\u0442\u044b', 'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438_\u043f\u0440\u043e\u0435\u043a\u0442\u044b'},
        ),
    ]
