# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0008_auto_20170619_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_project',
            name='head_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category_project',
            name='head_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
