# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_auto_20170619_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_project',
            name='project_key',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solar.Category_project'),
        ),
    ]
