# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0010_auto_20170619_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'circle',
                'verbose_name': '\u0426\u044b\u0444\u0440\u0430',
                'verbose_name_plural': '\u0426\u044b\u0444\u0440\u044b',
            },
        ),
    ]
