# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_cicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cicle',
            new_name='Circle',
        ),
    ]
