# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0012_auto_20170621_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
