# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0015_project_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('general', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'img_Service',
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430_\u0441\u0435\u0440\u0432\u0438\u0441',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438_\u0441\u0435\u0440\u0432\u0438\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('main', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Service',
                'verbose_name': '\u0421\u0435\u0440\u0432\u0438\u0441',
                'verbose_name_plural': '\u0421\u0435\u0440\u0432\u0438\u0441\u044b',
            },
        ),
        migrations.AddField(
            model_name='img_service',
            name='Service_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solar.Service'),
        ),
    ]
