# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0016_auto_20170622_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Price',
                'verbose_name': '\u0426\u0435\u043d\u0430',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='content',
        ),
    ]
