# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0017_auto_20170622_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Price_item',
                'verbose_name': '\u0426\u0435\u043d\u0430_\u043c',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b_\u043c',
            },
        ),
    ]
