# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0019_auto_20170622_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_item',
            name='price_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solar.Price'),
        ),
    ]
