# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0020_price_item_price_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solar.Price')),
            ],
            options={
                'db_table': 'Profit',
                'verbose_name': '\u0414\u043e\u0445\u043e\u0434',
                'verbose_name_plural': '\u0414\u043e\u0445\u043e\u0434\u044b',
            },
        ),
    ]
