# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0021_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Price_add',
                'verbose_name': '\u0426\u0435\u043d\u044b_\u0434\u043e\u043f_\u0438\u043d\u0444\u043e',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b_\u0434\u043e\u043f_\u0438\u043d\u0444\u043e',
            },
        ),
    ]
