# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0022_price_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
            options={
                'db_table': 'Articles',
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='Articles_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Articles_tag',
                'verbose_name': '\u0422\u0435\u0433_\u043a_\u0441\u0442\u0430\u0442\u044c\u044f\u043c',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438_\u043a_\u0441\u0442\u0430\u0442\u044c\u044f\u043c',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='tag_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solar.Articles_tag'),
        ),
    ]
