# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0023_auto_20170623_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
