# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0024_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
