# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0026_auto_20170625_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='head_ua',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='head_ua',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_button_ua',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_ua',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category_project',
            name='head_ua',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='head_ua',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='text_ua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
