# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-25 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0027_auto_20170625_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='head_ua',
            new_name='head_uk',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='text_ua',
            new_name='text_uk',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='head_ua',
            new_name='head_uk',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='text_button_ua',
            new_name='text_button_uk',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='text_ua',
            new_name='text_uk',
        ),
        migrations.RenameField(
            model_name='category_project',
            old_name='head_ua',
            new_name='head_uk',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='head_ua',
            new_name='head_uk',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='text_ua',
            new_name='text_uk',
        ),
    ]
