# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0029_article_main_partner_price_main_project_main_service_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
