# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0032_auto_20170626_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metatitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'metatitle',
            },
        ),
    ]
