# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-29 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0035_auto_20170629_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='head_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='head_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='head_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='text_uk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
