# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-30 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0036_auto_20170629_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='text',
        ),
        migrations.RemoveField(
            model_name='price',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='price',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='price',
            name='text_uk',
        ),
    ]
