# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0038_auto_20170704_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed_back_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=700, null=True)),
                ('email', models.CharField(blank=True, max_length=700, null=True)),
                ('phone', models.CharField(blank=True, max_length=700, null=True)),
                ('subject', models.CharField(blank=True, max_length=700, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date_f', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feed_back_letter',
            },
        ),
        migrations.CreateModel(
            name='Feed_back_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('date_f', models.DateField(blank=True, null=True)),
                ('worked', models.BooleanField(default=False)),
                ('recall', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'feed_back_phone',
            },
        ),
    ]
