# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0039_feed_back_letter_feed_back_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_main',
            name='head_en',
        ),
        migrations.RemoveField(
            model_name='article_main',
            name='head_ru',
        ),
        migrations.RemoveField(
            model_name='article_main',
            name='head_uk',
        ),
        migrations.RemoveField(
            model_name='article_main',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='article_main',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='article_main',
            name='text_uk',
        ),
        migrations.AddField(
            model_name='service',
            name='head_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='head_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='head_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_uk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
