# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-04 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0040_auto_20170704_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_back_letter',
            name='date_f',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed_back_phone',
            name='date_f',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
