# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0041_auto_20170704_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_back_letter',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed_back_phone',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
