# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-17 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0042_auto_20170704_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_main',
            name='head_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article_main',
            name='head_ru',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article_main',
            name='head_uk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article_main',
            name='text_en',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='article_main',
            name='text_ru',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='article_main',
            name='text_uk',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
